os: Visual Studio 2017

version: 0.5.3.{build}

configuration: Release

# Do not build on tags (GitHub only)
skip_tags: true

# Do not build when changing these files
skip_commits:
  files:
  - LICENSE.md
  - README.md

branches:
  only:
    - release
  
init:
  - git config --global core.autocrlf input  

before_build:
  - dotnet --info
  - nuget restore  

build:
  parallel: true                 # enable MSBuild parallel builds
  project: Cashew.sln    # path to Visual Studio solution or project   
  verbosity: normal

after_build:
  - dotnet pack .\src\Cashew\Cashew.csproj --configuration Release  
  - dotnet pack .\src\Cashew.Adapters.CacheManager\Cashew.Adapters.CacheManager.csproj --configuration Release  

test:
  assemblies:
    - '**\*.Tests.dll'

artifacts:
  - path: '**\Cashew.*.nupkg' # find all NuGet packages recursively
